[package]
name = "nyefan-org"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
publish = false

[dependencies]
sycamore = "0.9.1"
pulldown-cmark = {version = "0.12.2", features = ["simd", "html"]}
tracing = "0.1.41"
tracing-subscriber = "0.3.19"